#!/usr/bin/env python

'''
Project Euler problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
Fib_max = input("\nPlease enter maximum Fib number: ")

Fib_1 = 1
Fib_2 = 2
Sum = 0

while Fib_1 <= Fib_max:

	if Fib_1 % 2 == 0:
		Sum = Sum + Fib_1

	Fib_2 = Fib_2 + Fib_1
	Fib_1 = Fib_2 - Fib_1

print "\nThe sum of even Fibonacci terms from from 1 to " + str(Fib_max) + " is " + str(Sum) + "\n"
		